import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { TourSession, TranscriptChunk } from './transcriptDatabase';

export interface TourExportData {
  session: TourSession;
  chunks: TranscriptChunk[];
}

export class TranscriptExportService {
  /**
   * Generates a beautifully styled PDF and opens the native Share sheet.
   */
  static async exportToPdf(data: TourExportData): Promise<void> {
    const formattedDate = new Date(data.session.createdAt).toLocaleDateString(undefined, {
      dateStyle: 'full',
    });
    const durationMinutes = Math.ceil(data.session.durationMs / 60000);

    const rowsHtml = data.chunks
      .map((chunk) => {
        const time = new Date(chunk.timestampMs).toISOString().substring(14, 19);
        return `
          <div class="row">
            <span class="time">${time}</span>
            <div class="content">
              <div class="translated">${chunk.translatedText}</div>
              <div class="original">${chunk.originalText}</div>
            </div>
          </div>
        `;
      })
      .join('');

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; color: #1E293B; background: #FFF; }
            .header { border-bottom: 2px solid #E2E8F0; padding-bottom: 16px; margin-bottom: 20px; }
            .title { font-size: 22px; font-weight: 700; color: #0F172A; margin: 0 0 6px 0; }
            .meta { font-size: 12px; color: #64748B; display: flex; gap: 16px; }
            .badge { background: #EEF2F6; padding: 2px 8px; border-radius: 4px; font-weight: 600; }
            .row { display: flex; margin-bottom: 14px; page-break-inside: avoid; }
            .time { font-size: 11px; color: #94A3B8; width: 50px; flex-shrink: 0; font-family: monospace; }
            .content { flex: 1; }
            .translated { font-size: 14px; font-weight: 600; color: #0F172A; line-height: 1.4; }
            .original { font-size: 12px; color: #64748B; font-style: italic; margin-top: 2px; }
            .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #94A3B8; border-top: 1px solid #E2E8F0; padding-top: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1 class="title">${data.session.title}</h1>
            <div class="meta">
              <span>📅 ${formattedDate}</span>
              <span>⏱️ ${durationMinutes} min</span>
              <span class="badge">${data.session.sourceLang.toUpperCase()} ➔ ${data.session.targetLang.toUpperCase()}</span>
            </div>
          </div>
          <div class="transcript-list">
            ${rowsHtml}
          </div>
          <div class="footer">
            Generated by TourCast
          </div>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `Export: ${data.session.title}`,
      UTI: 'com.adobe.pdf',
    });
  }

  /**
   * Generates a plain text file (.txt) with timestamped utterances.
   */
  static async exportToPlainText(data: TourExportData): Promise<void> {
    const header = `=== ${data.session.title} ===nDate: ${new Date(data.session.createdAt).toLocaleString()}nLanguages: ${data.session.sourceLang} -> ${data.session.targetLang}nn`;

    const body = data.chunks
      .map((c) => {
        const time = new Date(c.timestampMs).toISOString().substring(14, 19);
        return `[${time}] ${c.translatedText}n(${c.originalText})n`;
      })
      .join('n');

    const fullContent = header + body;
    const sanitizedTitle = data.session.title.replace(/[^a-zA-Z0-9_-]/g, '_');
    const fileUri = `${FileSystem.cacheDirectory}${sanitizedTitle}_transcript.txt`;

    await FileSystem.writeAsStringAsync(fileUri, fullContent, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    await Sharing.shareAsync(fileUri, {
      mimeType: 'text/plain',
      dialogTitle: `Export: ${data.session.title}`,
    });
  }
}
